config/routes.rb
Employee::Application.routes.draw do
  get "home/index"

   root 'home#index'

    resources :admin

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	
  end

  def create
  	#debugger
  	@user = User.new
  	@user.name = params["name"]
  	@user.address = params["address"]
  	@user.gender = params["gender"]
  	@user.dob = params["dob"]
    if @user.save
  	  redirect_to admin_path(:id)
    end
  end

  def show
    @users = User.all
  end

  def edit
    
    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])
      if @user.update(params[:user].permit(:name, :address, :gender, :dob))
        redirect_to admin_path(:id)
      else
        render 'edit'
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_path(:id)

  end

  private
	  #def user_params
	 	#params.require(:user).permit(:name ,:address, :gender, :dob)
	  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/edit.html.erb
<h2>Edit Employee Information</h2>

<%= form_for @user, :url => { :action => "update" } do |f| %>
	<table>
		<tr>
			<td><%= f.label :Name %> </td>
	  		<td><%= f.text_field :name %></td>
	  	</tr>
	  	<tr>
	  		<td><%= f.label :Address %> </td>
	  		<td><%= f.text_area :address %></td>
	  	</tr>
	  	
	  	<tr>
			<td><%= f.label :Gender %></td>
	 		<td><%= f.radio_button(:gender, "Male") %> <%= f.label :Male %> <%= f.radio_button(:gender, "Female") %> <%= f.label :Female %></td>
	 	</tr>
	 	<tr>
	 		<td><%= f.label :Date_Of_Birth %></td>
	 		<td><%= f.text_field :dob %></td>
	 	</tr>
	 </table>
	 	<p><%= f.submit %></p>


<% end %>

app/views/admin/index.html.erb
<h2>Create Employee</h2>


<%= form_tag(method: "post") do %>
	<table>
		<tr>
			<td><%= label_tag("Name") %> </td>
	  		<td><%= text_field_tag("name") %></td>
	  	</tr>
	  	<tr>
	  		<td><%= label_tag("Address: ") %> </td>
	  		<td><%= text_area_tag("address") %></td>
	  	</tr>
	  	
	  	<tr>
			<td><%= label_tag("Gender") %></td>
	 		<td><%= radio_button_tag(:gender, "Male") %> <%= label_tag("Male") %> <%= radio_button_tag(:gender, "Female") %> <%= label_tag("Female") %></td>
	 	</tr>
	 	<tr>
	 		<td><%= label_tag("Date Of Birth") %></td>
	 		<td><%= text_field_tag("dob") %></td>
	 	</tr>
	 </table>
	 	<p><%= check_box_tag("accept") %> <%= label_tag("Accept terms & condition")%></p>
	 	<p><%= submit_tag("Save") %></p>


<% end %>

app/views/admin/new.html.erb
<h2>Create Employee</h2>


<%= form_tag(method: "post") do %>
	<table>
		<tr>
			<td><%= label_tag("Name") %> </td>
	  		<td><%= text_field_tag("name") %></td>
	  	</tr>
	  	<tr>
	  		<td><%= label_tag("Address: ") %> </td>
	  		<td><%= text_area_tag("address") %></td>
	  	</tr>
	  	<tr>
	  		<td><%= label_tag("city") %></td>
	  		<td><%= select_tag(:city, options_for_select([['Select', 0], ['Faridabad', 1],['Delhi', 2], ['Noida', 3], ['Gurgaon', 4]])) %></td>
	  	</tr>
	  	<tr>
			<td><%= label_tag("Gender") %></td>
	 		<td><%= radio_button_tag(:gender, "Male") %> <%= label_tag("Male") %> <%= radio_button_tag(:gender, "Female") %> <%= label_tag("Female") %></td>
	 	<tr>
	 		<td><%= label_tag("Date Of Birth") %></td>
	 		<td><%= text_field_tag("dob") %></td>
	 	</tr>
	 </table>
	 	<p><%= check_box_tag("accept") %> <%= label_tag("Accept terms & condition")%></p>
	 	<p><%= submit_tag("Save") %></p>

	 	 	
<% end %>

app/views/admin/show.html.erb
<h2>Employee Information</h2>

<table border = "1">
	<tr>
		<td><strong>Name</strong></td>
		<td><strong>Address</strong></td>
		<td><strong>Gender</strong></td>
		<td><strong>Date Of Birth</strong></td>
	</tr>
	
	<% @users.each do |user| %>

	<tr>
		<td><%= user.name %></td>
		<td><%= user.address %></td>
		<td><%= user.gender %></td>
		<td><%= user.dob %></td>
		<td><%= link_to "Edit", edit_admin_path(user) %></td>
		<td><%= link_to 'Destroy', admin_path(user) ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
	
	</tr>
	<% end %>
</table>

<%= link_to "Back", root_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/index_rails.html.erb
<h2>Enter Employee Infromation</h2>

<%= label_tag("Name") %> 
  <%= text_field_tag("name") %><br>

<%= label_tag("Address") %> 
  <%= text_area_tag("address") %><br>

<%= label_tag("Gender") %> 
  <%= radio_button_tag(:gender, "Male") %>
    <%= label_tag("Male") %>
  <%= radio_button_tag(:gender, "Female") %>
    <%= label_tag("Male") %><br>

<%= label_tag("Date Of Birth") %>
 <%= text_field_tag("dob") %><br>

<%= check_box_tag("accept") %>
<%= label_tag("Accept terms & condition")%><br>

<%= submit_tag("Save") %>

<%= date_field(:date, "employee") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Employee</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>